In [1]:
import numpy as np


In [3]:
lst= [1,2,3,4]

# np.array

In [4]:
arr= np.array(lst)

In [7]:
print(arr)
#prints the content of the array

[1 2 3 4]


In [6]:
arr
#gives out the list converted to arrray by np.array

array([1, 2, 3, 4])

In [8]:
math = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(math)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# np.arange

In [60]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# linspace

In [21]:
np.linspace(0,5,100)


array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [22]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.random.rand(5)
#5 random number in btw 0 and 1

array([0.16478095, 0.18349696, 0.19288577, 0.89594537, 0.63350211])

In [25]:
np.random.rand(5,5)

array([[0.79881374, 0.25835331, 0.96251474, 0.51455184, 0.19231561],
       [0.64921719, 0.75600745, 0.5933392 , 0.36583206, 0.88674916],
       [0.49799452, 0.31842226, 0.33762917, 0.74163001, 0.05883399],
       [0.28970997, 0.17586364, 0.95092413, 0.22614449, 0.08654453],
       [0.61784124, 0.16992431, 0.71425174, 0.4457399 , 0.21521395]])

In [27]:
#for normal distribultion
np.random.randn(4)

array([1.4395086 , 1.71300735, 0.41231262, 0.40606168])

In [36]:
#for random integer btw two numbers and like 10 integers

rando=np.random.randint(1,100,10)

In [33]:
arr= np.arange(25)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
rando.max()

97

In [38]:
rando.min()

31

In [40]:
rando.argmax()

3

In [41]:
rando.argmin()

4

In [43]:
rando.shape

(10,)

In [47]:
rando.reshape(5,2)

array([[54, 95],
       [62, 97],
       [31, 56],
       [42, 81],
       [38, 47]])

In [48]:
rando.shape

(10,)

# Indexing and slicing

In [50]:
arr= np.arange(1,21,2)

In [51]:
arr


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [53]:
arr[1]

3

In [54]:
arr[1:3]

array([3, 5])

In [55]:
solo=arr.copy()

In [56]:
solo


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [57]:
solo[:]= 100

In [58]:
solo

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [59]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [64]:
aer= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [69]:
aer

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
aer[0]

array([1, 2, 3])

In [70]:
aer[1,2]

6

In [71]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [72]:
arr[arr>10]

array([11, 13, 15, 17, 19])

In [74]:
arr= np.arange(50).reshape(5,10)

In [75]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])